development:
  adapter: postgresql
  database: fission_app_development
  host: localhost
  pool: 5
  timeout: 5000
  username: fission
  password: fission

test:
  adapter: postgresql
  database: fission_app_test
  host: localhost
  pool: 5
  timeout: 5000
  username: fission
  password: fission

production:
  adapter: postgresql
  database: fission_app
  host: localhost
  pool: 5
  timeout: 5000
  username: fission
  password: fission
